/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'todzhang' at '17-1-13 下午9:37' with Gradle 3.2.1
 *
 * @author todzhang, @date 17-1-13 下午9:37
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
